import type { Metadata } from "next";
import "./globals.css";
import Header from "./ui/Header";
import { quicksand } from "../../public/fonts";
import Head from 'next/head'; // Asegúrate de importar Head desde 'next/head'
import Footer from "./ui/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
      <link
        precedence="default"
        rel="stylesheet"
        type="text/css"
        charSet="UTF-8"
        href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
      />
      <link
        precedence="default"
        rel="stylesheet"
        type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
      />
    </html>
  );
}